/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CacheInfoResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CachesApi
 */
@Ignore
public class CachesApiTest {

    private final CachesApi api = new CachesApi();

    /**
     * Clears a cache
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clearCacheTest() throws ApiException {
        String cacheName = null;
        String nodeName = null;
        Long response = api.clearCache(cacheName, nodeName);

        // TODO: test validations
    }
    /**
     * Gets cache info
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCacheInfoTest() throws ApiException {
        String cacheName = null;
        String nodeName = null;
        CacheInfoResponse response = api.getCacheInfo(cacheName, nodeName);

        // TODO: test validations
    }
    /**
     * Lists caches
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCachesTest() throws ApiException {
        List<String> response = api.listCaches();

        // TODO: test validations
    }
}
