/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AbstractField;
import io.swagger.client.model.DocRef;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataSourcesApi
 */
@Ignore
public class DataSourcesApiTest {

    private final DataSourcesApi api = new DataSourcesApi();

    /**
     * Fetch data source fields
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchDataSourceFieldsTest() throws ApiException {
        DocRef body = null;
        List<AbstractField> response = api.fetchDataSourceFields(body);

        // TODO: test validations
    }
}
