/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.EntityEvent;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EntityEventsApi
 */
@Ignore
public class EntityEventsApiTest {

    private final EntityEventsApi api = new EntityEventsApi();

    /**
     * Sends an entity event
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fireEntityEventTest() throws ApiException {
        EntityEvent body = null;
        String nodeName = null;
        Boolean response = api.fireEntityEvent(body, nodeName);

        // TODO: test validations
    }
}
