/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.FindStoredQueryCriteria;
import io.swagger.client.model.ResultPageStoredQuery;
import io.swagger.client.model.StoredQuery;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StoredQueriesApi
 */
@Ignore
public class StoredQueriesApiTest {

    private final StoredQueriesApi api = new StoredQueriesApi();

    /**
     * Create a stored query
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createStoredQueryTest() throws ApiException {
        StoredQuery body = null;
        StoredQuery response = api.createStoredQuery(body);

        // TODO: test validations
    }
    /**
     * Delete a stored query
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteStoredQueryTest() throws ApiException {
        StoredQuery body = null;
        Boolean response = api.deleteStoredQuery(body);

        // TODO: test validations
    }
    /**
     * Fetch a stored query
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchStoredQueryTest() throws ApiException {
        StoredQuery body = null;
        StoredQuery response = api.fetchStoredQuery(body);

        // TODO: test validations
    }
    /**
     * Find stored queries
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findStoredQueriesTest() throws ApiException {
        FindStoredQueryCriteria body = null;
        ResultPageStoredQuery response = api.findStoredQueries(body);

        // TODO: test validations
    }
    /**
     * Update a stored query
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateStoredQueryTest() throws ApiException {
        StoredQuery body = null;
        StoredQuery response = api.updateStoredQuery(body);

        // TODO: test validations
    }
}
