/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DocRef;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * Base64EncodedDocumentData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class Base64EncodedDocumentData {
  @SerializedName("dataMap")
  private Map<String, String> dataMap = null;

  @SerializedName("docRef")
  private DocRef docRef = null;

  public Base64EncodedDocumentData dataMap(Map<String, String> dataMap) {
    this.dataMap = dataMap;
    return this;
  }

  public Base64EncodedDocumentData putDataMapItem(String key, String dataMapItem) {
    if (this.dataMap == null) {
      this.dataMap = new HashMap<String, String>();
    }
    this.dataMap.put(key, dataMapItem);
    return this;
  }

   /**
   * Get dataMap
   * @return dataMap
  **/
  @Schema(description = "")
  public Map<String, String> getDataMap() {
    return dataMap;
  }

  public void setDataMap(Map<String, String> dataMap) {
    this.dataMap = dataMap;
  }

  public Base64EncodedDocumentData docRef(DocRef docRef) {
    this.docRef = docRef;
    return this;
  }

   /**
   * Get docRef
   * @return docRef
  **/
  @Schema(description = "")
  public DocRef getDocRef() {
    return docRef;
  }

  public void setDocRef(DocRef docRef) {
    this.docRef = docRef;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Base64EncodedDocumentData base64EncodedDocumentData = (Base64EncodedDocumentData) o;
    return Objects.equals(this.dataMap, base64EncodedDocumentData.dataMap) &&
        Objects.equals(this.docRef, base64EncodedDocumentData.docRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataMap, docRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Base64EncodedDocumentData {\n");
    
    sb.append("    dataMap: ").append(toIndentedString(dataMap)).append("\n");
    sb.append("    docRef: ").append(toIndentedString(docRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
