/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BuildInfo;
import io.swagger.client.model.ClusterNodeInfoItem;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ClusterNodeInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class ClusterNodeInfo {
  @SerializedName("buildInfo")
  private BuildInfo buildInfo = null;

  @SerializedName("discoverTime")
  private String discoverTime = null;

  @SerializedName("endpointUrl")
  private String endpointUrl = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("itemList")
  private List<ClusterNodeInfoItem> itemList = null;

  @SerializedName("nodeName")
  private String nodeName = null;

  @SerializedName("ping")
  private Long ping = null;

  public ClusterNodeInfo buildInfo(BuildInfo buildInfo) {
    this.buildInfo = buildInfo;
    return this;
  }

   /**
   * Get buildInfo
   * @return buildInfo
  **/
  @Schema(description = "")
  public BuildInfo getBuildInfo() {
    return buildInfo;
  }

  public void setBuildInfo(BuildInfo buildInfo) {
    this.buildInfo = buildInfo;
  }

  public ClusterNodeInfo discoverTime(String discoverTime) {
    this.discoverTime = discoverTime;
    return this;
  }

   /**
   * Get discoverTime
   * @return discoverTime
  **/
  @Schema(description = "")
  public String getDiscoverTime() {
    return discoverTime;
  }

  public void setDiscoverTime(String discoverTime) {
    this.discoverTime = discoverTime;
  }

  public ClusterNodeInfo endpointUrl(String endpointUrl) {
    this.endpointUrl = endpointUrl;
    return this;
  }

   /**
   * Get endpointUrl
   * @return endpointUrl
  **/
  @Schema(description = "")
  public String getEndpointUrl() {
    return endpointUrl;
  }

  public void setEndpointUrl(String endpointUrl) {
    this.endpointUrl = endpointUrl;
  }

  public ClusterNodeInfo error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @Schema(description = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public ClusterNodeInfo itemList(List<ClusterNodeInfoItem> itemList) {
    this.itemList = itemList;
    return this;
  }

  public ClusterNodeInfo addItemListItem(ClusterNodeInfoItem itemListItem) {
    if (this.itemList == null) {
      this.itemList = new ArrayList<ClusterNodeInfoItem>();
    }
    this.itemList.add(itemListItem);
    return this;
  }

   /**
   * Get itemList
   * @return itemList
  **/
  @Schema(description = "")
  public List<ClusterNodeInfoItem> getItemList() {
    return itemList;
  }

  public void setItemList(List<ClusterNodeInfoItem> itemList) {
    this.itemList = itemList;
  }

  public ClusterNodeInfo nodeName(String nodeName) {
    this.nodeName = nodeName;
    return this;
  }

   /**
   * Get nodeName
   * @return nodeName
  **/
  @Schema(description = "")
  public String getNodeName() {
    return nodeName;
  }

  public void setNodeName(String nodeName) {
    this.nodeName = nodeName;
  }

  public ClusterNodeInfo ping(Long ping) {
    this.ping = ping;
    return this;
  }

   /**
   * Get ping
   * @return ping
  **/
  @Schema(description = "")
  public Long getPing() {
    return ping;
  }

  public void setPing(Long ping) {
    this.ping = ping;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterNodeInfo clusterNodeInfo = (ClusterNodeInfo) o;
    return Objects.equals(this.buildInfo, clusterNodeInfo.buildInfo) &&
        Objects.equals(this.discoverTime, clusterNodeInfo.discoverTime) &&
        Objects.equals(this.endpointUrl, clusterNodeInfo.endpointUrl) &&
        Objects.equals(this.error, clusterNodeInfo.error) &&
        Objects.equals(this.itemList, clusterNodeInfo.itemList) &&
        Objects.equals(this.nodeName, clusterNodeInfo.nodeName) &&
        Objects.equals(this.ping, clusterNodeInfo.ping);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buildInfo, discoverTime, endpointUrl, error, itemList, nodeName, ping);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterNodeInfo {\n");
    
    sb.append("    buildInfo: ").append(toIndentedString(buildInfo)).append("\n");
    sb.append("    discoverTime: ").append(toIndentedString(discoverTime)).append("\n");
    sb.append("    endpointUrl: ").append(toIndentedString(endpointUrl)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    itemList: ").append(toIndentedString(itemList)).append("\n");
    sb.append("    nodeName: ").append(toIndentedString(nodeName)).append("\n");
    sb.append("    ping: ").append(toIndentedString(ping)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
