/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.User;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * FilterUsersRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class FilterUsersRequest {
  @SerializedName("quickFilterInput")
  private String quickFilterInput = null;

  @SerializedName("users")
  private List<User> users = null;

  public FilterUsersRequest quickFilterInput(String quickFilterInput) {
    this.quickFilterInput = quickFilterInput;
    return this;
  }

   /**
   * Get quickFilterInput
   * @return quickFilterInput
  **/
  @Schema(description = "")
  public String getQuickFilterInput() {
    return quickFilterInput;
  }

  public void setQuickFilterInput(String quickFilterInput) {
    this.quickFilterInput = quickFilterInput;
  }

  public FilterUsersRequest users(List<User> users) {
    this.users = users;
    return this;
  }

  public FilterUsersRequest addUsersItem(User usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<User>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  @Schema(description = "")
  public List<User> getUsers() {
    return users;
  }

  public void setUsers(List<User> users) {
    this.users = users;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterUsersRequest filterUsersRequest = (FilterUsersRequest) o;
    return Objects.equals(this.quickFilterInput, filterUsersRequest.quickFilterInput) &&
        Objects.equals(this.users, filterUsersRequest.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quickFilterInput, users);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterUsersRequest {\n");
    
    sb.append("    quickFilterInput: ").append(toIndentedString(quickFilterInput)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
