/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FilterFieldDefinition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class FilterFieldDefinition {
  @SerializedName("defaultField")
  private Boolean defaultField = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("filterQualifier")
  private String filterQualifier = null;

  public FilterFieldDefinition defaultField(Boolean defaultField) {
    this.defaultField = defaultField;
    return this;
  }

   /**
   * Get defaultField
   * @return defaultField
  **/
  @Schema(description = "")
  public Boolean isDefaultField() {
    return defaultField;
  }

  public void setDefaultField(Boolean defaultField) {
    this.defaultField = defaultField;
  }

  public FilterFieldDefinition displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public FilterFieldDefinition filterQualifier(String filterQualifier) {
    this.filterQualifier = filterQualifier;
    return this;
  }

   /**
   * Get filterQualifier
   * @return filterQualifier
  **/
  @Schema(description = "")
  public String getFilterQualifier() {
    return filterQualifier;
  }

  public void setFilterQualifier(String filterQualifier) {
    this.filterQualifier = filterQualifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterFieldDefinition filterFieldDefinition = (FilterFieldDefinition) o;
    return Objects.equals(this.defaultField, filterFieldDefinition.defaultField) &&
        Objects.equals(this.displayName, filterFieldDefinition.displayName) &&
        Objects.equals(this.filterQualifier, filterFieldDefinition.filterQualifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultField, displayName, filterQualifier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterFieldDefinition {\n");
    
    sb.append("    defaultField: ").append(toIndentedString(defaultField)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    filterQualifier: ").append(toIndentedString(filterQualifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
