/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * JobNodeInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class JobNodeInfo {
  @SerializedName("currentTaskCount")
  private Integer currentTaskCount = null;

  @SerializedName("lastExecutedTime")
  private Long lastExecutedTime = null;

  @SerializedName("scheduleReferenceTime")
  private Long scheduleReferenceTime = null;

  public JobNodeInfo currentTaskCount(Integer currentTaskCount) {
    this.currentTaskCount = currentTaskCount;
    return this;
  }

   /**
   * Get currentTaskCount
   * @return currentTaskCount
  **/
  @Schema(description = "")
  public Integer getCurrentTaskCount() {
    return currentTaskCount;
  }

  public void setCurrentTaskCount(Integer currentTaskCount) {
    this.currentTaskCount = currentTaskCount;
  }

  public JobNodeInfo lastExecutedTime(Long lastExecutedTime) {
    this.lastExecutedTime = lastExecutedTime;
    return this;
  }

   /**
   * Get lastExecutedTime
   * @return lastExecutedTime
  **/
  @Schema(description = "")
  public Long getLastExecutedTime() {
    return lastExecutedTime;
  }

  public void setLastExecutedTime(Long lastExecutedTime) {
    this.lastExecutedTime = lastExecutedTime;
  }

  public JobNodeInfo scheduleReferenceTime(Long scheduleReferenceTime) {
    this.scheduleReferenceTime = scheduleReferenceTime;
    return this;
  }

   /**
   * Get scheduleReferenceTime
   * @return scheduleReferenceTime
  **/
  @Schema(description = "")
  public Long getScheduleReferenceTime() {
    return scheduleReferenceTime;
  }

  public void setScheduleReferenceTime(Long scheduleReferenceTime) {
    this.scheduleReferenceTime = scheduleReferenceTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobNodeInfo jobNodeInfo = (JobNodeInfo) o;
    return Objects.equals(this.currentTaskCount, jobNodeInfo.currentTaskCount) &&
        Objects.equals(this.lastExecutedTime, jobNodeInfo.lastExecutedTime) &&
        Objects.equals(this.scheduleReferenceTime, jobNodeInfo.scheduleReferenceTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentTaskCount, lastExecutedTime, scheduleReferenceTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobNodeInfo {\n");
    
    sb.append("    currentTaskCount: ").append(toIndentedString(currentTaskCount)).append("\n");
    sb.append("    lastExecutedTime: ").append(toIndentedString(lastExecutedTime)).append("\n");
    sb.append("    scheduleReferenceTime: ").append(toIndentedString(scheduleReferenceTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
