/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LoginResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class LoginResponse {
  @SerializedName("loginSuccessful")
  private Boolean loginSuccessful = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("requirePasswordChange")
  private Boolean requirePasswordChange = null;

  public LoginResponse loginSuccessful(Boolean loginSuccessful) {
    this.loginSuccessful = loginSuccessful;
    return this;
  }

   /**
   * Get loginSuccessful
   * @return loginSuccessful
  **/
  @Schema(description = "")
  public Boolean isLoginSuccessful() {
    return loginSuccessful;
  }

  public void setLoginSuccessful(Boolean loginSuccessful) {
    this.loginSuccessful = loginSuccessful;
  }

  public LoginResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public LoginResponse requirePasswordChange(Boolean requirePasswordChange) {
    this.requirePasswordChange = requirePasswordChange;
    return this;
  }

   /**
   * Get requirePasswordChange
   * @return requirePasswordChange
  **/
  @Schema(description = "")
  public Boolean isRequirePasswordChange() {
    return requirePasswordChange;
  }

  public void setRequirePasswordChange(Boolean requirePasswordChange) {
    this.requirePasswordChange = requirePasswordChange;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginResponse loginResponse = (LoginResponse) o;
    return Objects.equals(this.loginSuccessful, loginResponse.loginSuccessful) &&
        Objects.equals(this.message, loginResponse.message) &&
        Objects.equals(this.requirePasswordChange, loginResponse.requirePasswordChange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loginSuccessful, message, requirePasswordChange);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginResponse {\n");
    
    sb.append("    loginSuccessful: ").append(toIndentedString(loginSuccessful)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    requirePasswordChange: ").append(toIndentedString(requirePasswordChange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
