/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Message;
import io.swagger.client.model.ResourceKey;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResourceGeneration
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class ResourceGeneration {
  @SerializedName("messageList")
  private List<Message> messageList = null;

  @SerializedName("resourceKey")
  private ResourceKey resourceKey = null;

  public ResourceGeneration messageList(List<Message> messageList) {
    this.messageList = messageList;
    return this;
  }

  public ResourceGeneration addMessageListItem(Message messageListItem) {
    if (this.messageList == null) {
      this.messageList = new ArrayList<Message>();
    }
    this.messageList.add(messageListItem);
    return this;
  }

   /**
   * Get messageList
   * @return messageList
  **/
  @Schema(description = "")
  public List<Message> getMessageList() {
    return messageList;
  }

  public void setMessageList(List<Message> messageList) {
    this.messageList = messageList;
  }

  public ResourceGeneration resourceKey(ResourceKey resourceKey) {
    this.resourceKey = resourceKey;
    return this;
  }

   /**
   * Get resourceKey
   * @return resourceKey
  **/
  @Schema(description = "")
  public ResourceKey getResourceKey() {
    return resourceKey;
  }

  public void setResourceKey(ResourceKey resourceKey) {
    this.resourceKey = resourceKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceGeneration resourceGeneration = (ResourceGeneration) o;
    return Objects.equals(this.messageList, resourceGeneration.messageList) &&
        Objects.equals(this.resourceKey, resourceGeneration.resourceKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageList, resourceKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceGeneration {\n");
    
    sb.append("    messageList: ").append(toIndentedString(messageList)).append("\n");
    sb.append("    resourceKey: ").append(toIndentedString(resourceKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
