/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Result;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The response to a search request, that may or may not contain results. The results may only be a partial set if an iterative screech was requested
 */
@Schema(description = "The response to a search request, that may or may not contain results. The results may only be a partial set if an iterative screech was requested")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class SearchResponse {
  @SerializedName("complete")
  private Boolean complete = null;

  @SerializedName("errors")
  private List<String> errors = null;

  @SerializedName("highlights")
  private List<String> highlights = new ArrayList<String>();

  @SerializedName("results")
  private List<Result> results = null;

  public SearchResponse complete(Boolean complete) {
    this.complete = complete;
    return this;
  }

   /**
   * Get complete
   * @return complete
  **/
  @Schema(description = "")
  public Boolean isComplete() {
    return complete;
  }

  public void setComplete(Boolean complete) {
    this.complete = complete;
  }

  public SearchResponse errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public SearchResponse addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @Schema(description = "")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public SearchResponse highlights(List<String> highlights) {
    this.highlights = highlights;
    return this;
  }

  public SearchResponse addHighlightsItem(String highlightsItem) {
    this.highlights.add(highlightsItem);
    return this;
  }

   /**
   * A list of strings to highlight in the UI that should correlate with the search query.
   * @return highlights
  **/
  @Schema(required = true, description = "A list of strings to highlight in the UI that should correlate with the search query.")
  public List<String> getHighlights() {
    return highlights;
  }

  public void setHighlights(List<String> highlights) {
    this.highlights = highlights;
  }

  public SearchResponse results(List<Result> results) {
    this.results = results;
    return this;
  }

  public SearchResponse addResultsItem(Result resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<Result>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @Schema(description = "")
  public List<Result> getResults() {
    return results;
  }

  public void setResults(List<Result> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponse searchResponse = (SearchResponse) o;
    return Objects.equals(this.complete, searchResponse.complete) &&
        Objects.equals(this.errors, searchResponse.errors) &&
        Objects.equals(this.highlights, searchResponse.highlights) &&
        Objects.equals(this.results, searchResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(complete, errors, highlights, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponse {\n");
    
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    highlights: ").append(toIndentedString(highlights)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
