/*
 * Stroom API
 * Various APIs for interacting with Stroom and its data
 *
 * OpenAPI spec version: v1/v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * SolrSynchState
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-13T17:13:49.037+01:00[Europe/London]")
public class SolrSynchState {
  @SerializedName("lastSynchronized")
  private Long lastSynchronized = null;

  @SerializedName("messages")
  private List<String> messages = null;

  public SolrSynchState lastSynchronized(Long lastSynchronized) {
    this.lastSynchronized = lastSynchronized;
    return this;
  }

   /**
   * Get lastSynchronized
   * @return lastSynchronized
  **/
  @Schema(description = "")
  public Long getLastSynchronized() {
    return lastSynchronized;
  }

  public void setLastSynchronized(Long lastSynchronized) {
    this.lastSynchronized = lastSynchronized;
  }

  public SolrSynchState messages(List<String> messages) {
    this.messages = messages;
    return this;
  }

  public SolrSynchState addMessagesItem(String messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<String>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @Schema(description = "")
  public List<String> getMessages() {
    return messages;
  }

  public void setMessages(List<String> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolrSynchState solrSynchState = (SolrSynchState) o;
    return Objects.equals(this.lastSynchronized, solrSynchState.lastSynchronized) &&
        Objects.equals(this.messages, solrSynchState.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastSynchronized, messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolrSynchState {\n");
    
    sb.append("    lastSynchronized: ").append(toIndentedString(lastSynchronized)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
